version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"