version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80" # Frontend'in çalıştığı port
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000" # Backend'in çalıştığı port
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/notes
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: